LANGUAGE="en"
USERNAME="subsworld"
PASSWORD="subsworld"
SUBDB_URL="http://api.thesubdb.com"
OPENSUBTITLES_URL="http://api.opensubtitles.org/xml-rpc"
USER_AGENT_SUBSDB="SubDB/1.0 (subsworld/1.0; http://github.com/mugdhaadhav/subtitle-downloader)"
USER_AGENT_OPENSUBS="TemporaryUserAgent"